### ISSUE TITLE
Re-setting key can lead to deletion

### ISSUE THREAD

**Issue by mhofman** [WebReflection/weak-value#1]
The finalizer currently blindly erases the entry. If an entry is reset, the finalizer for the previously registered value will remove the current entry.

Not tested:
```js
const k = 'key';
const wv = new WeakValue();

const v = (() => {
  const v1 = { foo: 1};
  const v2 = { foo: 2};
  wv.set(k, v1);
  wv.set(k, v2);
  return v2;
})();

setTimeout(() => {
  gc();
  const shouldBeV = wv.get(k);
  console.log(shouldBeV); // undefined;
});
```

You might be able to use the weakref object as an unregister token.

**Comment by mhofman** [comment]
A quick Googling reminded me of @devsnek's [weak-value-map package](https://github.com/devsnek/weak-value-map) which already implements this. That package handles unregister with the WeakRef as token.

**Comment by yairopro** [comment]
For the time, devsnek/weak-value-map doesn't support commonjs.

**Comment by WebReflection** [comment]
I think I've completely missed this issue ... it's fixed though, but your test does something wrong, imho, you need to compare `shouldBeV === v` or it gets lost (which is expected).

Test added to this library though 👋

**Comment by mhofman** [comment]
I don't believe the change you made fixes the issue.

The test I provided above wasn't mean to assert, but to highlight what currently happens.

Please look at @devsnek's package, the logic there is correct.

**Comment by WebReflection** [comment]
@mhofman I think the latest logic is the current one. Everything works as expected, and undefined is expected too if you invoke gc() and don't keep the `v` around. The unregister dance is now correct (AFAIK) and it happens either on `has` or on `set`.
